CID-Portal/Models/TravelRequest.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelRequest()
        {
            this.TRHotelInfoes = new HashSet<TRHotelInfo>();
            this.Trips = new HashSet<Trip>();
        }
    
        public int TRID { get; set; }
        public string RequesterNotes { get; set; }
        public System.DateTime RequestedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> TRStatusID { get; set; }
        public Nullable<int> FlightStatus { get; set; }
        public Nullable<double> TotalFlightCost { get; set; }
        public Nullable<int> HotelStatus { get; set; }
        public Nullable<int> VisaStatus { get; set; }
        public Nullable<int> HRLetterStatus { get; set; }
        public Nullable<int> InvitationLetterStatus { get; set; }
        public string OperationsNotes { get; set; }
        public Nullable<System.DateTime> ChangeRequestDate { get; set; }
        public string ChangeRequestReason { get; set; }
        public string TravelRequestForm { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> ExcelStatusId { get; set; }
        public Nullable<double> TotalReissueCost { get; set; }
        public Nullable<int> Rating { get; set; }
        public string RatingComment { get; set; }
        public Nullable<int> TotalFlightCostCurrencyID { get; set; }
        public Nullable<double> TotalHotelCost { get; set; }
        public Nullable<int> TotalHotelCostCurrencyID { get; set; }
        public Nullable<double> TotalReissueCost2 { get; set; }
        public Nullable<double> TotalReissueCost3 { get; set; }
        public Nullable<double> FlightRefundCost { get; set; }
        public Nullable<double> ForcastedFlightsCost { get; set; }
        public Nullable<double> ForcastedAccommodationCost { get; set; }
        public Nullable<double> ForcastedExpenses { get; set; }
        public Nullable<double> ForcastedTotal { get; set; }
        public Nullable<double> TotalFlightCost2 { get; set; }
        public Nullable<int> TotalFlightCostCurrencyID2 { get; set; }
        public Nullable<int> FlightInvoiceStatus { get; set; }
        public Nullable<int> FlightInvoiceStatus2 { get; set; }
        public Nullable<int> TotalReissueStatus { get; set; }
        public Nullable<int> TotalReissueStatus2 { get; set; }
        public Nullable<int> TotalReissueStatus3 { get; set; }
        public Nullable<int> VisaInvoiceStatus { get; set; }
        public Nullable<int> HoteInvoiceStatus { get; set; }
        public Nullable<int> PoStatus { get; set; }
        public Nullable<int> FlightRefundInvoiceStatus { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Currency Currency2 { get; set; }
        public virtual TRItemsStatu TRItemsStatu { get; set; }
        public virtual TRItemsStatu TRItemsStatu1 { get; set; }
        public virtual TRItemsStatu TRItemsStatu2 { get; set; }
        public virtual TRItemsStatu TRItemsStatu3 { get; set; }
        public virtual TRItemsStatu TRItemsStatu4 { get; set; }
        public virtual TRItemsStatu TRItemsStatu5 { get; set; }
        public virtual TravelRequestStatu TravelRequestStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRHotelInfo> TRHotelInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trip> Trips { get; set; }
    }
}

CID-Portal/Models/TravelRequestView.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelRequestView
    {
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> NumOfDays { get; set; }
        public Nullable<int> WorkingDays { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public string Routes { get; set; }
        public string TRStatus { get; set; }
        public string FlightStatus { get; set; }
        public string HotelStatus { get; set; }
        public string VisaStatus { get; set; }
        public string HRLetterStatus { get; set; }
        public string FlightInvoiceStatus { get; set; }
        public string FlightInvoiceStatus2 { get; set; }
        public string ReissueInvoiceStatus { get; set; }
        public string ReissueInvoiceStatus2 { get; set; }
        public string ReissueInvoiceStatus3 { get; set; }
        public string HotelInvoiceStatus { get; set; }
        public string VisaInvoiceStatus { get; set; }
        public string FlightRefundInvoiceStatus { get; set; }
        public Nullable<double> FlightCost { get; set; }
        public string FlightCostCurrency { get; set; }
        public Nullable<double> FlightCost2 { get; set; }
        public string FlightCost2Currency { get; set; }
        public Nullable<double> ReissueCost { get; set; }
        public Nullable<double> ReissueCost2 { get; set; }
        public Nullable<double> ReissueCost3 { get; set; }
        public Nullable<double> FlightRefund { get; set; }
        public Nullable<double> HotelCost { get; set; }
        public string HotelCostCurrency { get; set; }
        public string RequesterNotes { get; set; }
        public string OperationsNotes { get; set; }
        public string TripType { get; set; }
    }
}

CID-Portal/Controllers/TravelRequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using VacationsPortal.Models;
using VacationsPortal.ViewModels;

namespace VacationsPortal.Controllers
{
    public class TravelRequestsController : Controller
    {
        private readonly CIDvNEXtEntities _db = new CIDvNEXtEntities();

        public bool IsAuthorized()
        {
            //var loggedUserEmail = "v-gamoha@microsoft.com";
            var loggedUserEmail = ClaimsPrincipal.Current.FindFirst(ClaimTypes.Name).Value;
            var authUser = _db.AuthUsers.FirstOrDefault(u => u.Email == loggedUserEmail);
            if (authUser?.Privilege != null && (Privilege.Admin == (Privilege)authUser.Privilege ||
                                                Privilege.Travel == (Privilege)authUser.Privilege))
            {
                return true;
            }
            return false;
        }

        public TravelRequestView SetTRvmFields(TravelRequest travelRequest, Trip trip,
                                                    Dictionary<int, string> statusesDic)
        {
            var tRvm = new TravelRequestView
            {
                Id = travelRequest.TRID,
                TRStatus = travelRequest.TravelRequestStatu.Status,
                FlightCost = travelRequest.TotalFlightCost,
                FlightCost2 = travelRequest.TotalFlightCost2,
                ReissueCost = travelRequest.TotalReissueCost,
                ReissueCost2 = travelRequest.TotalReissueCost2,
                ReissueCost3 = travelRequest.TotalReissueCost3,
                FlightRefund = travelRequest.FlightRefundCost,
                HotelCost = travelRequest.TotalHotelCost,
                RequesterNotes = travelRequest.RequesterNotes,
                OperationsNotes = travelRequest.OperationsNotes,
                TripType = trip.Business != null && (bool)trip.Business ? "Business" : "Training",
                EmployeeName = trip.Employee.contact.FullName,
                StartDate = trip.StartDate,
                EndDate = trip.EndDate,
                NumOfDays = trip.NumberofDays,
                WorkingDays = trip.NumberofWorkingDays,
                ModifiedOn = trip.ModifiedOn,
                IsCanceled = trip.IsCanceled,
                Routes = trip.Routes.ToList()[0].City.Name
            };

            for (var i = 1; i < trip.Routes.Count; i++)
            {
                tRvm.Routes += ',' + trip.Routes.ToList()[i].City.Name;
            }
            if (travelRequest.FlightStatus != null)
            {
                if (statusesDic.ContainsKey((int)travelRequest.FlightStatus))
                {
                    tRvm.FlightStatus = statusesDic[(int)travelRequest.FlightStatus];
                }
            }
            if (travelRequest.HotelStatus != null)
            {
                if (statusesDic.ContainsKey((int)travelRequest.HotelStatus))
                {
                    tRvm.HotelStatus = statusesDic[(int)travelRequest.HotelStatus];
                }
            }
            if (travelRequest.VisaStatus != null)
            {
                if (statusesDic.ContainsKey((int)travelRequest.VisaStatus))
                {
                    tRvm.VisaStatus = statusesDic[(int)travelRequest.VisaStatus];
                }
            }
            if (travelRequest.HRLetterStatus != null)
            {
                if (statusesDic.ContainsKey((int)travelRequest.HRLetterStatus))
                {
                    tRvm.HRLetterStatus = statusesDic[(int)travelRequest.HRLetterStatus];
                }
            }
            if (travelRequest.Currency != null)
            {
                tRvm.FlightCostCurrency = travelRequest.Currency.CurrencyName;
            }
            if (travelRequest.Currency2 != null)
            {
                tRvm.FlightCost2Currency = travelRequest.Currency2.CurrencyName;
            }
            if (travelRequest.Currency1 != null)
            {
                tRvm.HotelCostCurrency = travelRequest.Currency1.CurrencyName;
            }

            if (travelRequest.FlightInvoiceStatus != null)
            {
                tRvm.FlightInvoiceStatus = travelRequest.FlightInvoiceStatus == 0 ? "Not Invoiced" : "Invoiced";
            }
            if (travelRequest.FlightInvoiceStatus2 != null)
            {
                tRvm.FlightInvoiceStatus2 = travelRequest.FlightInvoiceStatus2 == 0 ? "Not Invoiced" : "Invoiced";
            }
            if (travelRequest.FlightRefundInvoiceStatus != null)
            {
                tRvm.FlightRefundInvoiceStatus = travelRequest.FlightRefundInvoiceStatus == 0 ? "Not Invoiced" : "Invoiced";
            }
            if (travelRequest.HoteInvoiceStatus != null)
            {
                tRvm.HotelInvoiceStatus = travelRequest.HoteInvoiceStatus == 0 ? "Not Invoiced" : "Invoiced";
            }
            if (travelRequest.VisaInvoiceStatus != null)
            {
                tRvm.VisaInvoiceStatus = travelRequest.VisaInvoiceStatus == 0 ? "Not Invoiced" : "Invoiced";
            }
            if (travelRequest.TotalReissueStatus != null)
            {
                tRvm.ReissueInvoiceStatus = travelRequest.TotalReissueStatus == 0 ? "Not Invoiced" : "Invoiced";
            }
            if (travelRequest.TotalReissueStatus2 != null)
            {
                tRvm.ReissueInvoiceStatus2 = travelRequest.TotalReissueStatus2 == 0 ? "Not Invoiced" : "Invoiced";
            }
            if (travelRequest.TotalReissueStatus3 != null)
            {
                tRvm.ReissueInvoiceStatus3 = travelRequest.TotalReissueStatus3 == 0 ? "Not Invoiced" : "Invoiced";
            }

            return tRvm;
        }

        public List<TravelRequestView> SetTRvmList(List<TravelRequest> travelRequests)
        {
            var statusesDic = _db.TRItemsStatus.ToDictionary(status => status.Id, status => status.Status);
            var travelRequestsvm = new List<TravelRequestView>();
            foreach (var travelRequest in travelRequests)
            {
                foreach (var trip in travelRequest.Trips.ToList())
                {
                    travelRequestsvm.Add(SetTRvmFields(travelRequest, trip, statusesDic));
                }
            }
            return travelRequestsvm;
        }


        public TravelRequestView_Archive SetTRvmFieldsArchive(TravelRequest travelRequest, Trip trip,
                                                    Dictionary<int, string> statusesDic)
        {
            var tRvm = new TravelRequestView_Archive
            {
                Id = travelRequest.TRID,
                TRStatus = travelRequest.TravelRequestStatu.Status,
                FlightCost = travelRequest.TotalFlightCost,
                FlightCost2 = travelRequest.TotalFlightCost2,
                ReissueCost = travelRequest.TotalReissueCost,
                ReissueCost2 = travelRequest.TotalReissueCost2,
                ReissueCost3 = travelRequest.TotalReissueCost3,
                FlightRefund = travelRequest.FlightRefundCost,
                HotelCost = travelRequest.TotalHotelCost,
                RequesterNotes = travelRequest.RequesterNotes,
                OperationsNotes = travelRequest.OperationsNotes,
                TripType = trip.Business != null && (bool)trip.Business ? "Business" : "Training",
                EmployeeName = trip.Employee.contact.FullName,
                StartDate = trip.StartDate,
                EndDate = trip.EndDate,
                NumOfDays = trip.NumberofDays,
                WorkingDays = trip.NumberofWorkingDays,
                ModifiedOn = trip.ModifiedOn,
                IsCanceled = trip.IsCanceled,
                Routes = trip.Routes.ToList()[0].City.Name
            };

            for (var i = 1; i < trip.Routes.Count; i++)
            {
                tRvm.Routes += ',' + trip.Routes.ToList()[i].City.Name;
            }
            if (travelRequest.FlightStatus != null)
            {
                if (statusesDic.ContainsKey((int)travelRequest.FlightStatus))
                {
                    tRvm.FlightStatus = statusesDic[(int)travelRequest.FlightStatus];
                }
            }
            if (travelRequest.HotelStatus != null)
            {
                if (statusesDic.ContainsKey((int)travelRequest.HotelStatus))
                {
                    tRvm.HotelStatus = statusesDic[(int)travelRequest.HotelStatus];
                }
            }
            if (travelRequest.VisaStatus != null)
            {
                if (statusesDic.ContainsKey((int)travelRequest.VisaStatus))
                {
                    tRvm.VisaStatus = statusesDic[(int)travelRequest.VisaStatus];
                }
            }
            if (travelRequest.HRLetterStatus != null)
            {
                if (statusesDic.ContainsKey((int)travelRequest.HRLetterStatus))
                {
                    tRvm.HRLetterStatus = statusesDic[(int)travelRequest.HRLetterStatus];
                }
            }
            if (travelRequest.Currency != null)
            {
                tRvm.FlightCostCurrency = travelRequest.Currency.CurrencyName;
            }
            if (travelRequest.Currency2 != null)
            {
                tRvm.FlightCost2Currency = travelRequest.Currency2.CurrencyName;
            }
            if (travelRequest.Currency1 != null)
            {
                tRvm.HotelCostCurrency = travelRequest.Currency1.CurrencyName;
            }

            if (travelRequest.FlightInvoiceStatus != null)
            {
                tRvm.FlightInvoiceStatus = travelRequest.FlightInvoiceStatus == 0 ? "Not Invoiced" : "Invoiced";
            }
            if (travelRequest.FlightInvoiceStatus2 != null)
            {

CID-Portal/Views/TravelRequests/Archive.cshtml
@model IEnumerable<VacationsPortal.Models.TravelRequestView_Archive>

@{
    ViewBag.Title = "Travel Requests Archive";
}

<h2>Travel Requests Archive</h2>
<p>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index","Trips")'">
        Trips
    </button>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index","NonTrips")'">
        Non-Trips
    </button>
    <a class="btn btn-primary" onclick="return GetArchiveYears()">
        Archive
    </a>
</p>

<style>
    div.dt-buttons {
        float: right;
        margin-left: 10px;
    }
</style>
<table class="mdl-data-table" id="tb">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumOfDays)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WorkingDays)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsCanceled)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Routes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TRStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotelStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VisaStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HRLetterStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightCostCurrency)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightCost2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightCost2Currency)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReissueCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReissueCost2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReissueCost3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightRefund)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotelCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotelCostCurrency)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequesterNotes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OperationsNotes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TripType)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Hotel", "../TRHotelInfos/Details/" + item.Id) |
                    @Html.ActionLink("Visa", "../Visas/Details/" + item.Id)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmployeeName)
                </td>
                <td>
                    @if (item.StartDate != null)
                    {
                        @item.StartDate.Value.ToShortDateString()
                    }
                </td>
                <td>
                    @if (item.EndDate != null)
                    {
                        @item.EndDate.Value.ToShortDateString()
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumOfDays)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkingDays)
                </td>
                <td>
                    @if (item.ModifiedOn != null)
                    {
                        @item.ModifiedOn.Value.ToShortDateString()
                    }
                </td>
                <td>
                    @if (item.IsCanceled != null)
                    {
                        if ((bool)item.IsCanceled)
                        {
                            @Html.Raw("YES")
                        }
                        else
                        {
                            @Html.Raw("NO")
                        }
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Routes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TRStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HotelStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VisaStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HRLetterStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightCost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightCostCurrency)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightCost2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightCost2Currency)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReissueCost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReissueCost2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReissueCost3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightRefund)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HotelCost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HotelCostCurrency)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequesterNotes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OperationsNotes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TripType)
                </td>
            </tr>
        }
    </tbody>
</table>

@section styles{
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css">
}

@section Scripts
{
    @Scripts.Render("~/bundles/datatables")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>

    <script>
        $(document).ready(function () {
            $("#tb").DataTable({
                dom: 'lBfrtip',
                buttons: [
                    'excel'
                ],
                columnDefs: [
                    {
                        className: 'mdl-data-table__cell--non-numeric'
                    }
                ],
                fixedHeader: true,
                "order": [[1, "desc"]]
            });
        });

        function GetArchiveYears() {
            var id = prompt("Enter Fiscal Year (e.g. 2016-2017)");
            var url = '@Url.Action("Archive", "TravelRequests", new { id = "__id__" })';
            location.href = url.replace('__id__', id);
        }

    </script>

}