CID-Portal/Models/AuthUser.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Privilege { get; set; }
    }
}

CID-Portal/Controllers/AuthUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using VacationsPortal.Models;

namespace VacationsPortal.Controllers
{
    public class AuthUsersController : Controller
    {
        private readonly CIDvNEXtEntities _db = new CIDvNEXtEntities();

        public bool IsAuthorized()
        {
            //var loggedUserEmail = "v-gamoha@microsoft.com";
            var loggedUserEmail = ClaimsPrincipal.Current.FindFirst(ClaimTypes.Name).Value;
            var authUser = _db.AuthUsers.FirstOrDefault(u => u.Email == loggedUserEmail);
            if (authUser?.Privilege != null && Privilege.Admin == (Privilege)authUser.Privilege)
            {
                return true;
            }
            return false;
        }

        // GET: AuthUsers
        public ActionResult Index()
        {
            if (IsAuthorized())
            {
                return View(_db.AuthUsers.ToList());
            }

            ViewBag.ErrorMsg = "Not authenticated user.";
            return View("Error");
        }

        
        // GET: AuthUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AuthUsers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AuthUser authUser)
        {
            if (ModelState.IsValid)
            {
                _db.AuthUsers.Add(authUser);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(authUser);
        }

        // GET: AuthUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var authUser = _db.AuthUsers.Find(id);
            if (authUser == null)
            {
                return HttpNotFound();
            }

            return View(authUser);
        }

        // POST: AuthUsers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AuthUser authUser)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(authUser).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(authUser);
        }

        // GET: AuthUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var authUser = _db.AuthUsers.Find(id);
            if (authUser == null)
            {
                return HttpNotFound();
            }
            _db.AuthUsers.Remove(authUser);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CID-Portal/Views/AuthUsers/Create.cshtml
@using VacationsPortal.Controllers
@model VacationsPortal.Models.AuthUser

@{
    ViewBag.Title = "New User";
}

<h2>New User</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "v-example@microsoft.com", required = "required" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Privilege, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Privilege", EnumHelper.GetSelectList(typeof(Privilege)), "-select privilege-", new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.Privilege, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CID-Portal/Views/AuthUsers/Edit.cshtml
@using VacationsPortal.Controllers
@model VacationsPortal.Models.AuthUser

@{
    ViewBag.Title = "Edit User";
}

<h2>Edit User</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "v-example@microsoft.com", required = "required" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Privilege, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Privilege", EnumHelper.GetSelectList(typeof(Privilege)), "-select privilege-", new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.Privilege, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CID-Portal/Views/AuthUsers/Index.cshtml
@using VacationsPortal.Controllers
@model IEnumerable<VacationsPortal.Models.AuthUser>

@{
    ViewBag.Title = "Authenticated Users";
}

<h2>Authenticated Users</h2>

<p>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create","AuthUsers")'">
        + New User
    </button>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index","Trips")'">
        Travel
    </button>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index","Employees")'">
        Employees
    </button>
</p>

<style>
    div.dt-buttons {
        float: right;
        margin-left: 10px;
    }
</style>

<table class="mdl-data-table" id="tb">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Privilege)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>

                    @if (item.Privilege != null)
                    {
                        var priv = (Privilege) item.Privilege;
                        @Html.DisplayFor(modelItem => priv)
                    }

                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    <a href="@("/AuthUsers/Delete/" + item.Id.ToString())"
                       onclick="return confirm('Are you sure that you want to delete this user?');">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>

</table>


@section styles{
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css">
}

@section Scripts
{
    @Scripts.Render("~/bundles/datatables")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>

    <script>
        $(document).ready(function () {
            $("#tb").DataTable({
                dom: 'lBfrtip',
                buttons: [
                    'excel'
                ],
                columnDefs: [
                    {
                        className: 'mdl-data-table__cell--non-numeric'
                    }
                ],
                fixedHeader: true,
                "order": [[0, "asc"]]
            });
        });
    </script>

}