CID-Portal/Models/PublicVacation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicVacation
    {
        public int VacationID { get; set; }
        public string Title { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}

CID-Portal/Controllers/PublicVacationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using VacationsPortal.Models;

namespace VacationsPortal.Controllers
{
    public class PublicVacationsController : Controller
    {
        private readonly CIDvNEXtEntities _db = new CIDvNEXtEntities();

        public bool IsAuthorized()
        {
            //var loggedUserEmail = "v-gamoha@microsoft.com";
            var loggedUserEmail = ClaimsPrincipal.Current.FindFirst(ClaimTypes.Name).Value;
            var authUser = _db.AuthUsers.FirstOrDefault(u => u.Email == loggedUserEmail);
            if (authUser?.Privilege != null && (Privilege.Admin == (Privilege)authUser.Privilege ||
                                                Privilege.Vacations == (Privilege)authUser.Privilege))
            {
                return true;
            }
            return false;
        }

        // GET: PublicVacations
        public ActionResult Index()
        {
            if (IsAuthorized())
            {
                return View(_db.PublicVacations.Where(v => v.StartDate.Year == DateTime.Now.Year ||
                                                           v.EndDate.Year == DateTime.Now.Year)
                                                           .ToList()
                                                           .OrderByDescending(v => v.StartDate)
                                                           .ThenByDescending(v => v.EndDate));
            }
            ViewBag.ErrorMsg = "Not authenticated user.";
            return View("Error");
        }

        // GET: PublicVacations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PublicVacations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PublicVacation publicVacation)
        {
            if (ModelState.IsValid)
            {
                _db.PublicVacations.Add(publicVacation);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(publicVacation);
        }

        // GET: PublicVacations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var publicVacation = _db.PublicVacations.Find(id);
            if (publicVacation == null)
            {
                return HttpNotFound();
            }
            return View(publicVacation);
        }

        // POST: PublicVacations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PublicVacation publicVacation)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(publicVacation).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(publicVacation);
        }

        // GET: PublicVacations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var publicVacation = _db.PublicVacations.Find(id);
            if (publicVacation == null)
            {
                return HttpNotFound();
            }
            _db.PublicVacations.Remove(publicVacation);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CID-Portal/Views/PublicVacations/Create.cshtml
@model VacationsPortal.Models.PublicVacation

@{
    ViewBag.Title = "Create";
}

<h2>Add Vacation</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", placeholder = "mm/dd/yyyy", required = "required" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", placeholder = "mm/dd/yyyy", required = "required" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CID-Portal/Views/PublicVacations/Edit.cshtml
@model VacationsPortal.Models.PublicVacation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Vacation</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VacationID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ var startDate = Model.StartDate.ToShortDateString();}
                @Html.EditorFor(model => startDate, new {htmlAttributes = new {@class = "form-control", placeholder = "mm/dd/yyyy", required = "required" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ var endDate = Model.EndDate.ToShortDateString();}
                @Html.EditorFor(model => endDate, new {htmlAttributes = new {@class = "form-control", placeholder = "mm/dd/yyyy", required = "required" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CID-Portal/Views/PublicVacations/Index.cshtml
@model IEnumerable<VacationsPortal.Models.PublicVacation>

@{
    ViewBag.Title = "Public Vacations";
}

<h2>Public Vacations</h2>

<p>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index","Employees")'">
        Employees
    </button>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create","PublicVacations")'">
        Add Vacation
    </button>
</p>

<style>
    div.dt-buttons {
        float: right;
        margin-left: 10px;
    }
</style>

<table class="mdl-data-table" id="tb">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @item.StartDate.ToShortDateString()
                </td>
                <td>
                    @item.EndDate.ToShortDateString()
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.VacationID })
                </td>
            </tr>
        }
    </tbody>

</table>


@section styles{
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css">
}

@section Scripts
{
    @Scripts.Render("~/bundles/datatables")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>

    <script>
        $(document).ready(function () {
            $("#tb").DataTable({
                dom: 'lBfrtip',
                buttons: [
                    'excel'
                ],
                columnDefs: [
                    {
                        className: 'mdl-data-table__cell--non-numeric'
                    }
                ],
                fixedHeader: true,
                "order": false
            });
        });
    </script>

}