CID-Portal/Models/Trip.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.CashInAdvances = new HashSet<CashInAdvance>();
            this.ExpensesReports = new HashSet<ExpensesReport>();
            this.Routes = new HashSet<Route>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> NumberofDays { get; set; }
        public Nullable<int> NumberofWorkingDays { get; set; }
        public Nullable<int> Status { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> Business { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<int> TRID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashInAdvance> CashInAdvances { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensesReport> ExpensesReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
        public virtual TravelRequest TravelRequest { get; set; }
    }
}

CID-Portal/Models/TripsView.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripsView
    {
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Country { get; set; }
        public Nullable<int> CIA_Id { get; set; }
        public string CIA_Status { get; set; }
        public Nullable<decimal> CIA_Amount_InCurrency { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<double> CIA_ExchangeRate { get; set; }
        public Nullable<decimal> CIA_Amount_InEGP { get; set; }
        public string CIA_Reason { get; set; }
        public Nullable<System.DateTime> OperationsApprovalDate { get; set; }
        public Nullable<int> ExpenseReportId { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ExpenseReportStatus { get; set; }
        public Nullable<double> TotalAmountInEGP { get; set; }
        public Nullable<double> CIAExpenseReport { get; set; }
        public Nullable<double> AmountToEmployeeInEGP { get; set; }
        public Nullable<decimal> SettledAmount { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public Nullable<decimal> RemainingBalance { get; set; }
        public string OperationsComment { get; set; }
    }
}

CID-Portal/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using VacationsPortal.Models;
using VacationsPortal.ViewModels;

namespace VacationsPortal.Controllers
{
    public class TripsController : Controller
    {
        private readonly CIDvNEXtEntities _db = new CIDvNEXtEntities();

        public bool IsAuthorized()
        {
            //var loggedUserEmail = "v-gamoha@microsoft.com";
            var loggedUserEmail = ClaimsPrincipal.Current.FindFirst(ClaimTypes.Name).Value;
            var authUser = _db.AuthUsers.FirstOrDefault(u => u.Email == loggedUserEmail);
            if (authUser?.Privilege != null && (Privilege.Admin == (Privilege)authUser.Privilege ||
                                                Privilege.Travel == (Privilege)authUser.Privilege))
            {
                return true;
            }
            return false;
        }

        public List<TripsView> SetTripsViewList(List<Trip> trips)
        {
            var tripsvm = new List<TripsView>();
            foreach (var trip in trips)
            {
                // Add trip basic data
                var tripvm = new TripsView()
                {
                    TripID = trip.Id,
                    EmployeeName = trip.Employee.contact.FullName,
                    StartDate = trip.StartDate,
                    EndDate = trip.EndDate,
                    Country = trip.Routes.ToList()[trip.Routes.Count - 2].Country.CountryName
                };

                if (trip.CashInAdvances.Count > 0 || trip.ExpensesReports.Count > 0)
                {
                    // Fill Trip CIA, plus its Expenses (if exist)
                    foreach (var cia in trip.CashInAdvances)
                    {
                        var tripvm2 = new TripsView
                        {
                            TripID = tripvm.TripID,
                            EmployeeName = tripvm.EmployeeName,
                            StartDate = tripvm.StartDate,
                            EndDate = tripvm.EndDate,
                            Country = tripvm.Country,
                            CIA_Id = cia.Id,
                            CIA_Status = cia.CashInAdvanceStatu.CashInAdvanceStatus,
                            CurrencyName = cia.Currency.CurrencyName,
                            CIA_Amount_InCurrency = cia.Amount ?? 0,
                            CIA_ExchangeRate = cia.ExchangeRate ?? 0,
                            CIA_Reason = cia.Reason,
                            OperationsApprovalDate = cia.OperationApprovalDate,
                            SettledAmount = cia.SettledAmount ?? 0,
                            SettlementDate = cia.SettlementDate,
                            OperationsComment = cia.OperationsComment
                        };
                        if (tripvm2.CIA_ExchangeRate != null)
                            tripvm2.CIA_Amount_InEGP = tripvm2.CIA_Amount_InCurrency *
                                                       (decimal)tripvm2.CIA_ExchangeRate;


                        if (cia.ExpensesReports.Count > 0)
                        {
                            foreach (var ciaExpensesReport in cia.ExpensesReports)
                            {
                                var tripvm3 = new TripsView
                                {
                                    TripID = tripvm2.TripID,
                                    EmployeeName = tripvm2.EmployeeName,
                                    StartDate = tripvm2.StartDate,
                                    EndDate = tripvm2.EndDate,
                                    Country = tripvm2.Country,
                                    CIA_Id = tripvm2.CIA_Id,
                                    CIA_Status = tripvm2.CIA_Status,
                                    CurrencyName = tripvm2.CurrencyName,
                                    CIA_Amount_InCurrency = tripvm2.CIA_Amount_InCurrency ?? 0,
                                    CIA_ExchangeRate = tripvm2.CIA_ExchangeRate ?? 0,
                                    CIA_Reason = tripvm2.CIA_Reason,
                                    OperationsApprovalDate = tripvm2.OperationsApprovalDate,
                                    ExpenseReportId = ciaExpensesReport.ID,
                                    SubmissionDate = ciaExpensesReport.SubmissionDate,
                                    ApprovalDate = ciaExpensesReport.ApprovalDate,
                                    ExpenseReportStatus = ciaExpensesReport.ExpenseReportStatu.StatusName,
                                    TotalAmountInEGP = ciaExpensesReport.TotalAmountInUSD ?? 0,
                                    CIAExpenseReport = ciaExpensesReport.CashInAdvance ?? 0,
                                    SettledAmount = ciaExpensesReport.SettledAmount ?? 0,
                                    SettlementDate = ciaExpensesReport.SettlementDate,
                                    OperationsComment = ciaExpensesReport.OperationsComment
                                };
                                if (tripvm3.CIA_ExchangeRate != null)
                                    tripvm3.CIA_Amount_InEGP = tripvm3.CIA_Amount_InCurrency *
                                                               (decimal)tripvm3.CIA_ExchangeRate;
                                tripvm3.AmountToEmployeeInEGP = (tripvm3.TotalAmountInEGP - tripvm3.CIAExpenseReport) ?? 0;
                                tripvm3.RemainingBalance = Math.Abs((decimal)tripvm3.AmountToEmployeeInEGP) - tripvm3.SettledAmount;

                                tripsvm.Add(tripvm3); // Trip with CIA and expenses
                            }
                        }
                        else
                        {
                            tripsvm.Add(tripvm2); // Trip with CIA only
                        }
                    }

                    // Trip expenses without CIA
                    foreach (var expense in trip.ExpensesReports)
                    {
                        if (expense.CashInAdvances.Count == 0)
                        {
                            var tripvm4 = tripvm;
                            tripvm4.ExpenseReportId = expense.ID;
                            tripvm4.SubmissionDate = expense.SubmissionDate;
                            tripvm4.ApprovalDate = expense.ApprovalDate;
                            tripvm4.ExpenseReportStatus = expense.ExpenseReportStatu.StatusName;
                            tripvm4.TotalAmountInEGP = expense.TotalAmountInUSD ?? 0;
                            tripvm4.CIAExpenseReport = expense.CashInAdvance ?? 0;
                            tripvm4.AmountToEmployeeInEGP = (tripvm4.TotalAmountInEGP - tripvm4.CIAExpenseReport) ?? 0;
                            tripvm4.SettledAmount = expense.SettledAmount ?? 0;
                            tripvm4.SettlementDate = expense.SettlementDate;
                            tripvm4.RemainingBalance = (decimal)tripvm4.AmountToEmployeeInEGP - tripvm4.SettledAmount;
                            tripvm4.OperationsComment = expense.OperationsComment;

                            tripsvm.Add(tripvm4); // Trip with Expenses only
                        }
                    }
                }
                else
                {
                    tripsvm.Add(tripvm); //Trip without any CIAs or Expenses
                }
            }
            return tripsvm;
        }

        public List<TripsView_Archive> SetTripsViewListArchive(List<Trip> trips)
        {
            var tripsvm = new List<TripsView_Archive>();
            foreach (var trip in trips)
            {
                // Add trip basic data
                var tripvm = new TripsView_Archive()
                {
                    TripID = trip.Id,
                    EmployeeName = trip.Employee.contact.FullName,
                    StartDate = trip.StartDate,
                    EndDate = trip.EndDate,
                    Country = trip.Routes.ToList()[trip.Routes.Count - 2].Country.CountryName
                };

                if (trip.CashInAdvances.Count > 0 || trip.ExpensesReports.Count > 0)
                {
                    // Fill Trip CIA, plus its Expenses (if exist)
                    foreach (var cia in trip.CashInAdvances)
                    {
                        var tripvm2 = new TripsView_Archive
                        {
                            TripID = tripvm.TripID,
                            EmployeeName = tripvm.EmployeeName,
                            StartDate = tripvm.StartDate,
                            EndDate = tripvm.EndDate,
                            Country = tripvm.Country,
                            CIA_Id = cia.Id,
                            CIA_Status = cia.CashInAdvanceStatu.CashInAdvanceStatus,
                            CurrencyName = cia.Currency.CurrencyName,
                            CIA_Amount_InCurrency = cia.Amount ?? 0,
                            CIA_ExchangeRate = cia.ExchangeRate ?? 0,
                            CIA_Reason = cia.Reason,
                            OperationsApprovalDate = cia.OperationApprovalDate,
                            SettledAmount = cia.SettledAmount ?? 0,
                            SettlementDate = cia.SettlementDate,
                            OperationsComment = cia.OperationsComment
                        };
                        if (tripvm2.CIA_ExchangeRate != null)
                            tripvm2.CIA_Amount_InEGP = tripvm2.CIA_Amount_InCurrency *
                                                       (decimal)tripvm2.CIA_ExchangeRate;


                        if (cia.ExpensesReports.Count > 0)
                        {
                            foreach (var ciaExpensesReport in cia.ExpensesReports)

CID-Portal/Views/Trips/Archive.cshtml
@using System.Globalization
@model IEnumerable<VacationsPortal.Models.TripsView_Archive>

@{
    ViewBag.Title = "Trips Archive";
}

<h2>Trips Archive</h2>
<p>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index","Trips")'">
        Trips
    </button>
    <button type="button" class="btn btn-primary" onclick="location.href = '@Url.Action("Index", "NonTrips")'">
        Non-Trips
    </button>
    <button type="button" class="btn btn-primary" onclick="location.href = '@Url.Action("Index", "TravelRequests")'">
        Travel Requests
    </button>
    <a class="btn btn-primary" onclick="return GetArchiveYears()">
        Archive
    </a>
</p>

<style>
    div.dt-buttons {
        float: right;
        margin-left: 10px;
    }
</style>

<table class="mdl-data-table" id="tb">
    <thead>
        <tr>
            <th>TRIP</th>
            <th colspan="6">CASH IN ADVANCE</th>
            <th colspan="7">EXPENSE</th>
            <th colspan="7">SETTLEMENT</th>
        </tr>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CIA_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CIA_Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CIA_Amount_InCurrency)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrencyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CIA_ExchangeRate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CIA_Amount_InEGP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CIA_Reason)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OperationsApprovalDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseReportId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubmissionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApprovalDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseReportStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalAmountInEGP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CIAExpenseReport)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AmountToEmployeeInEGP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SettledAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SettlementDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RemainingBalance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OperationsComment)
            </th>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TripID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmployeeName)
                </td>
                <td>
                    @if (item.StartDate != null)
                    {
                        @item.StartDate.Value.ToShortDateString()
                    }
                </td>
                <td>
                    @if (item.EndDate != null)
                    {
                        @item.EndDate.Value.ToShortDateString()
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CIA_Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CIA_Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CIA_Amount_InCurrency)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrencyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CIA_ExchangeRate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CIA_Amount_InEGP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CIA_Reason)
                </td>
                <td>
                    @if (item.OperationsApprovalDate != null)
                    {
                        @item.OperationsApprovalDate.Value.ToShortDateString()
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExpenseReportId)
                </td>
                <td>
                    @if (item.SubmissionDate.ToShortDateString() != "1/1/0001")
                    {
                        @item.SubmissionDate.ToShortDateString()
                    }
                </td>
                <td>
                    @if (item.ApprovalDate != null)
                    {
                        @item.ApprovalDate.Value.ToShortDateString()
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExpenseReportStatus)
                </td>
                <td>

                    @if (item.TotalAmountInEGP != null)
                    {
                        var x = Math.Round(item.TotalAmountInEGP.Value, 2);
                        @Html.DisplayFor(modelItem => x);
                    }

                </td>
                <td>
                    @if (item.CIAExpenseReport != null)
                    {
                        var x = Math.Round(item.CIAExpenseReport.Value, 2);
                        @Html.DisplayFor(modelItem => x);
                    }
                </td>
                <td>
                    @if (item.AmountToEmployeeInEGP != null)
                    {
                        var x = Math.Round(item.AmountToEmployeeInEGP.Value, 2);
                        @Html.DisplayFor(modelItem => x);
                    }
                </td>
                <td>
                    @*@if (item.SettledAmount != null)
                        {
                            var s = Math.Round(item.SettledAmount.Value, 2).ToString(CultureInfo.InvariantCulture);
                            @Html.ActionLink(s, "Edit", new { ExpId = item.ExpenseReportId, CIAId = item.CIA_Id })
                        }*@
                    @if (item.SettledAmount != null)
                    {
                        var x = Math.Round(item.SettledAmount.Value, 2);
                        @Html.DisplayFor(modelItem => x);
                    }
                </td>
                <td>
                    @if (item.SettlementDate != null)
                    {
                        @item.SettlementDate.Value.ToShortDateString()
                    }
                </td>
                <td>
                    @if (item.RemainingBalance != null)
                    {
                        var x = Math.Round(item.RemainingBalance.Value, 2);
                        @Html.DisplayFor(modelItem => x);
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OperationsComment)
                </td>
                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>*@
            </tr>
        }
    </tbody>
</table>

@section styles{
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css">
}

@section Scripts
{
    @Scripts.Render("~/bundles/datatables")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>

    <script>
        $(document).ready(function () {
            $("#tb").DataTable({
                dom: 'lBfrtip',
                buttons: [
                    'excel'
                ],
                columnDefs: [
                    {
                        className: 'mdl-data-table__cell--non-numeric'
                    }
                ],
                fixedHeader: true,
                "order": [[0, "desc"]]
            });
        });

        function GetArchiveYears() {
            var id = prompt("Enter Fiscal Year (e.g. 2016-2017)");
            var url = '@Url.Action("Archive", "Trips", new { id = "__id__" })';
            location.href = url.replace('__id__', id);
        }
    </script>

}

CID-Portal/Views/Trips/Edit.cshtml
@model VacationsPortal.ViewModels.SettlementViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Trip</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @if (Model.ExpensesReport == null)
    {
        @Html.HiddenFor(model => model.CashInAdvance.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.CashInAdvance.SettledAmount, "Settled Amount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CashInAdvance.SettledAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CashInAdvance.SettledAmount, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CashInAdvance.OperationsComment, "Operations Comment", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CashInAdvance.OperationsComment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CashInAdvance.OperationsComment, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CashInAdvance.CashInAdvanceStatus, "CIA Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CashInAdvance.CashInAdvanceStatus, ViewBag.CIAStatuses as SelectList, "-select status-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CashInAdvance.CashInAdvanceStatus, "", new { @class = "text-danger" })
            </div>
        </div>
    }
    else
    {
        @Html.HiddenFor(model => model.ExpensesReport.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.ExpensesReport.SettledAmount, "Settled Amount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpensesReport.SettledAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpensesReport.SettledAmount, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ExpensesReport.OperationsComment, "Operations Comment", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpensesReport.OperationsComment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpensesReport.OperationsComment, "", new { @class = "text-danger" })
            </div>
        </div>
        if (Model.CashInAdvance != null)
        {
            @Html.HiddenFor(model => model.CashInAdvance.Id)
            <div class="form-group">
                @Html.LabelFor(model => model.CashInAdvance.CashInAdvanceStatus, "CIA Status", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CashInAdvance.CashInAdvanceStatus, ViewBag.CIAStatuses as SelectList, "-select status-", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CashInAdvance.CashInAdvanceStatus, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        <div class="form-group">
            @Html.LabelFor(model => model.ExpensesReport.ExpenseReportStatu, "Expense Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ExpensesReport.StatusID, ViewBag.ExpenseStatuses as SelectList, "-select status-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExpensesReport.ExpenseReportStatu, "", new { @class = "text-danger" })
            </div>
        </div>
    }

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>